In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 1) data1 : 음식물쓰레기 데이터

In [ ]:
data1 = pd.read_csv('/content/drive/MyDrive/21 세미프로젝트_2차 (1)/데이터/01_음식물쓰레기_기본수정.csv',encoding='cp949')
data1

          base_date city    emd_cd emd_nm em_area_cd  em_cnt    em_g  pay_amt
0        2018-01-01  제주시  50110670    외도동     W6X062       2   15500      464
1        2018-01-01  제주시  50110630    아라동     W6XA97      25   59800     1787
2        2018-01-01  제주시  50110630    아라동     W6XA96       8   25350      758
3        2018-01-01  제주시  50110630    아라동     W6XA95      12   30000      898
4        2018-01-01  제주시  50110630    아라동     W6XA94      14   44050     1317
...             ...  ...       ...    ...        ...     ...     ...      ...
2208737  2021-06-30  제주시  50110250    한림읍     W6XEB4      12   58250     1743
2208738  2021-06-30  제주시  50110250    한림읍     W6XEB7      15  111000     3326
2208739  2021-06-30  제주시  50110250    한림읍     W6XEB8      21   48300     1444
2208740  2021-06-30  제주시  50110250    한림읍     W6XEA2       5   22050      661
2208741  2021-06-30  제주시  50110640    오라동     W6XAD5       2    2900       87

[2208742 rows x 8 columns]

In [ ]:
data1['year_date'] = data1['base_date'].str.split('-').str[0]
data1['month_date'] = data1['base_date'].str.split('-').str[1]
data1['day_date'] = data1['base_date'].str.split('-').str[2]
data1

          base_date city    emd_cd  ... year_date month_date  day_date
0        2018-01-01  제주시  50110670  ...      2018         01        01
1        2018-01-01  제주시  50110630  ...      2018         01        01
2        2018-01-01  제주시  50110630  ...      2018         01        01
3        2018-01-01  제주시  50110630  ...      2018         01        01
4        2018-01-01  제주시  50110630  ...      2018         01        01
...             ...  ...       ...  ...       ...        ...       ...
2208737  2021-06-30  제주시  50110250  ...      2021         06        30
2208738  2021-06-30  제주시  50110250  ...      2021         06        30
2208739  2021-06-30  제주시  50110250  ...      2021         06        30
2208740  2021-06-30  제주시  50110250  ...      2021         06        30
2208741  2021-06-30  제주시  50110640  ...      2021         06        30

[2208742 rows x 11 columns]

In [ ]:
data1[['year_date', 'month_date', 'day_date']] = data1[['year_date', 'month_date', 'day_date']].apply(pd.to_numeric)
data1

          base_date city    emd_cd  ... year_date month_date  day_date
0        2018-01-01  제주시  50110670  ...      2018          1         1
1        2018-01-01  제주시  50110630  ...      2018          1         1
2        2018-01-01  제주시  50110630  ...      2018          1         1
3        2018-01-01  제주시  50110630  ...      2018          1         1
4        2018-01-01  제주시  50110630  ...      2018          1         1
...             ...  ...       ...  ...       ...        ...       ...
2208737  2021-06-30  제주시  50110250  ...      2021          6        30
2208738  2021-06-30  제주시  50110250  ...      2021          6        30
2208739  2021-06-30  제주시  50110250  ...      2021          6        30
2208740  2021-06-30  제주시  50110250  ...      2021          6        30
2208741  2021-06-30  제주시  50110640  ...      2021          6        30

[2208742 rows x 11 columns]

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2208742 entries, 0 to 2208741
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   base_date   object
 1   city        object
 2   emd_cd      int64
 3   emd_nm      object
 4   em_area_cd  object
 5   em_cnt      int64
 6   em_g        int64
 7   pay_amt     int64
 8   year_date   int64
 9   month_date  int64
 10  day_date    int64
dtypes: int64(7), object(4)
memory usage: 185.4+ MB

### 3) data3 : 거주인구 데이터

In [ ]:
data3 = pd.read_csv('/content/drive/MyDrive/21 세미프로젝트_2차/원본데이터/01_제공데이터_update(210811)/03_거주인구_RESIDENT_POP.CSV',encoding='cp949')
data3

      base_year  base_month  city  ...  resid_reg_pop foreign_pop total_pop
0          2018           1   제주시  ...           5085         146      5231
1          2018           1   제주시  ...           4715          82      4797
2          2018           1   제주시  ...           7965         368      8333
3          2018           1   제주시  ...           7609         184      7793
4          2018           1  서귀포시  ...           9806         428     10234
...         ...         ...   ...  ...            ...         ...       ...
3607       2021           6   제주시  ...          10341        1140     11481
3608       2021           6   제주시  ...          12062         169     12231
3609       2021           6   제주시  ...          12238         161     12399
3610       2021           6  서귀포시  ...           2660          39      2699
3611       2021           6  서귀포시  ...           2597          18      2615

[3612 rows x 9 columns]

In [ ]:
grouped = data3[['resid_reg_pop','foreign_pop','total_pop']].groupby([data3['base_year'],data3['base_month'],data3['emd_cd'],data3['emd_nm']])
data3_2 = pd.DataFrame(grouped.sum()).reset_index()
data3_2

      base_year  base_month    emd_cd  ... resid_reg_pop  foreign_pop  total_pop
0          2018           1  50110250  ...         20889         3530      24419
1          2018           1  50110253  ...         34271          935      35206
2          2018           1  50110256  ...         15574          552      16126
3          2018           1  50110259  ...         23456          526      23982
4          2018           1  50110310  ...          8950          319       9269
...         ...         ...       ...  ...           ...          ...        ...
1801       2021           6  50130580  ...         10925          129      11054
1802       2021           6  50130590  ...         15084          193      15277
1803       2021           6  50130600  ...         13865          181      14046
1804       2021           6  50130610  ...         11563          305      11868
1805       2021           6  50130620  ...          3915          237       4152

[1806 rows x 7 columns]

### 4) data4 : 카드소비 데이터

In [ ]:
data4 = pd.read_csv('/content/drive/MyDrive/21 세미프로젝트_2차/원본데이터/01_제공데이터_update(210811)/04_음식관련 카드소비_CARD_SPENDING.CSV',encoding='cp949')
data4

         base_date  city    emd_cd  ... mct_cat_nm use_cnt    use_amt
0       2018-01-06   제주시  50110650  ...         한식    3643  127777300
1       2018-01-09   제주시  50110650  ...      패스트푸드     432    6711675
2       2018-01-15   제주시  50110650  ...      농축수산물     236   16089579
3       2018-01-15   제주시  50110650  ...    마트/슈퍼마켓    4031  121979867
4       2018-01-20   제주시  50110650  ...         식품     633   30410674
...            ...   ...       ...  ...        ...     ...        ...
544800  2020-10-16   제주시  XXXXXXXX  ...         배달       5     127250
544801  2019-08-31  서귀포시  XXXXXXXX  ...         배달       5      39974
544802  2020-10-03  서귀포시  XXXXXXXX  ...         배달      10     329832
544803  2020-10-23  서귀포시  XXXXXXXX  ...         배달       5      68715
544804  2020-12-21   제주시  XXXXXXXX  ...         배달      10     187452

[544805 rows x 8 columns]

In [ ]:
# '알수없음'버리기
# data4_2 = data4.copy()
data4_2 = data4[data4['emd_nm']!='알수없음']
data4_2

         base_date city    emd_cd  ... mct_cat_nm use_cnt    use_amt
0       2018-01-06  제주시  50110650  ...         한식    3643  127777300
1       2018-01-09  제주시  50110650  ...      패스트푸드     432    6711675
2       2018-01-15  제주시  50110650  ...      농축수산물     236   16089579
3       2018-01-15  제주시  50110650  ...    마트/슈퍼마켓    4031  121979867
4       2018-01-20  제주시  50110650  ...         식품     633   30410674
...            ...  ...       ...  ...        ...     ...        ...
544725  2020-05-26  제주시  50110520  ...         배달     445   10786980
544726  2020-12-08  제주시  50110520  ...         배달     513   11768033
544727  2020-04-30  제주시  50110520  ...         배달     486   11109119
544728  2020-05-28  제주시  50110520  ...         배달     353    8428342
544729  2018-03-21  제주시  50110520  ...         배달      34     615000

[530497 rows x 8 columns]

In [ ]:
data4_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 530497 entries, 0 to 544729
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   base_date   530497 non-null  object
 1   city        530497 non-null  object
 2   emd_cd      530497 non-null  object
 3   emd_nm      530497 non-null  object
 4   mct_cat_cd  530497 non-null  object
 5   mct_cat_nm  530497 non-null  object
 6   use_cnt     530497 non-null  int64
 7   use_amt     530497 non-null  int64
dtypes: int64(2), object(6)
memory usage: 56.4+ MB

In [ ]:
data4_2[['emd_cd']] = data4_2[['emd_cd']].apply(pd.to_numeric)
data4_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 530497 entries, 0 to 544729
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   base_date   530497 non-null  object
 1   city        530497 non-null  object
 2   emd_cd      530497 non-null  int64
 3   emd_nm      530497 non-null  object
 4   mct_cat_cd  530497 non-null  object
 5   mct_cat_nm  530497 non-null  object
 6   use_cnt     530497 non-null  int64
 7   use_amt     530497 non-null  int64
dtypes: int64(3), object(5)
memory usage: 56.4+ MB

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

#### 1) 마트/슈퍼마켓 : market

In [ ]:
market = data4_2[data4_2['mct_cat_cd']=='A00200']
market

         base_date city    emd_cd  ... mct_cat_nm use_cnt    use_amt
3       2018-01-15  제주시  50110650  ...    마트/슈퍼마켓    4031  121979867
14      2018-02-06  제주시  50110650  ...    마트/슈퍼마켓    3364   99018979
34      2018-04-20  제주시  50110650  ...    마트/슈퍼마켓    3532   94000829
43      2018-05-11  제주시  50110650  ...    마트/슈퍼마켓    3153   81716456
49      2018-05-19  제주시  50110650  ...    마트/슈퍼마켓    3901  133939526
...            ...  ...       ...  ...        ...     ...        ...
533642  2020-10-10  제주시  50110510  ...    마트/슈퍼마켓     255    8261834
533647  2020-05-15  제주시  50110510  ...    마트/슈퍼마켓     235    4964365
533657  2021-04-27  제주시  50110510  ...    마트/슈퍼마켓     188   13352301
533659  2020-10-08  제주시  50110510  ...    마트/슈퍼마켓     193    6287677
533733  2020-05-30  제주시  50110520  ...    마트/슈퍼마켓    2110   55790060

[54905 rows x 8 columns]

#### 2) 한식 : korean

In [ ]:
korean = data4_2[data4_2['mct_cat_cd']=='C00100']

#### 3) 양식~부페 : rest2

In [ ]:
rest = data4_2[(data4_2['mct_cat_cd'] == 'C00200') | (data4_2['mct_cat_cd'] == 'C00300') | (data4_2['mct_cat_cd'] == 'C00400') | (data4_2['mct_cat_cd'] == 'C00500') | (data4_2['mct_cat_cd'] == 'C00700')]
rest

         base_date city    emd_cd  ... mct_cat_nm use_cnt   use_amt
1       2018-01-09  제주시  50110650  ...      패스트푸드     432   6711675
6       2018-01-22  제주시  50110650  ...         양식      98   2912705
7       2018-01-26  제주시  50110650  ...         양식     182   7191382
9       2018-01-31  제주시  50110650  ...      패스트푸드     555   8944547
10      2018-02-01  제주시  50110650  ...         간식     846  10212423
...            ...  ...       ...  ...        ...     ...       ...
533748  2021-04-01  제주시  50110520  ...      아시아음식     162   5163795
533749  2018-09-03  제주시  50110520  ...         부페       5     68740
533750  2020-04-23  제주시  50110520  ...         간식     491   6233161
533751  2020-05-25  제주시  50110520  ...      패스트푸드     373   5281032
533752  2020-09-01  제주시  50110520  ...         간식     629   7318644

[222694 rows x 8 columns]

In [ ]:
grouped = rest[['use_cnt','use_amt']].groupby([rest['base_date'],rest['emd_cd']])
rest2 = pd.DataFrame(grouped.sum()).reset_index()
rest2

        base_date    emd_cd  use_cnt   use_amt
0      2018-01-01  50110250      329   7920125
1      2018-01-01  50110253      796  17246542
2      2018-01-01  50110256      153   3475691
3      2018-01-01  50110259      618  15811477
4      2018-01-01  50110310       74   1238302
...           ...       ...      ...       ...
54672  2021-06-30  50130580      343   6045306
54673  2021-06-30  50130590      568  10823052
54674  2021-06-30  50130600      492   6644781
54675  2021-06-30  50130610      392   6149728
54676  2021-06-30  50130620      115   2029857

[54677 rows x 4 columns]

#### 4) 주점 및 주류판매~농축수산물

In [ ]:
ect = data4_2[(data4_2['mct_cat_cd'] == 'C00900') | (data4_2['mct_cat_cd'] == 'C01000') | (data4_2['mct_cat_cd'] == 'C01200')]
grouped = ect[['use_cnt','use_amt']].groupby([ect['base_date'],ect['emd_cd']])
ect2 = pd.DataFrame(grouped.sum()).reset_index()
ect2

        base_date    emd_cd  use_cnt   use_amt
0      2018-01-01  50110250      388  15048512
1      2018-01-01  50110253      907  32167620
2      2018-01-01  50110256      256  10611197
3      2018-01-01  50110259      726  25014732
4      2018-01-01  50110310      103   3607476
...           ...       ...      ...       ...
54675  2021-06-30  50130580      306  12252879
54676  2021-06-30  50130590      432  17455408
54677  2021-06-30  50130600      347  16715797
54678  2021-06-30  50130610      438  70188519
54679  2021-06-30  50130620       80  10471102

[54680 rows x 4 columns]

#### 5) 배달 : deli

In [ ]:
deli = data4_2[data4_2['mct_cat_cd']=='C01400']
deli

         base_date city    emd_cd  ... mct_cat_nm use_cnt   use_amt
122370  2018-12-16  제주시  50110650  ...         배달     448   9832292
122371  2020-01-31  제주시  50110650  ...         배달     933  20519743
122372  2019-10-06  제주시  50110650  ...         배달     734  16651653
122373  2019-10-21  제주시  50110650  ...         배달     571  11292726
122374  2019-10-01  제주시  50110650  ...         배달     724  16066632
...            ...  ...       ...  ...        ...     ...       ...
544725  2020-05-26  제주시  50110520  ...         배달     445  10786980
544726  2020-12-08  제주시  50110520  ...         배달     513  11768033
544727  2020-04-30  제주시  50110520  ...         배달     486  11109119
544728  2020-05-28  제주시  50110520  ...         배달     353   8428342
544729  2018-03-21  제주시  50110520  ...         배달      34    615000

[50642 rows x 8 columns]

## 데이터셋 통합하기

### 1) data1 + total

In [ ]:
data3_2.columns

Index(['year_date', 'month_date', 'emd_cd', 'emd_nm', 'resid_reg_pop',
       'foreign_pop', 'total_pop'],
      dtype='object')

In [ ]:
data3_2.columns = ['year_date', 'month_date', 'emd_cd', 'emd_nm', 'resid_reg_pop', 'foreign_pop', 'total_pop']
data3_2

      year_date  month_date    emd_cd  ... resid_reg_pop  foreign_pop  total_pop
0          2018           1  50110250  ...         20889         3530      24419
1          2018           1  50110253  ...         34271          935      35206
2          2018           1  50110256  ...         15574          552      16126
3          2018           1  50110259  ...         23456          526      23982
4          2018           1  50110310  ...          8950          319       9269
...         ...         ...       ...  ...           ...          ...        ...
1801       2021           6  50130580  ...         10925          129      11054
1802       2021           6  50130590  ...         15084          193      15277
1803       2021           6  50130600  ...         13865          181      14046
1804       2021           6  50130610  ...         11563          305      11868
1805       2021           6  50130620  ...          3915          237       4152

[1806 rows x 7 columns]

In [ ]:
final = pd.merge(data1, data3_2, left_on=['year_date','month_date','emd_cd'], right_on=['year_date','month_date','emd_cd'], how='outer')
final

          base_date city    emd_cd  ... resid_reg_pop foreign_pop  total_pop
0        2018-01-01  제주시  50110670  ...         20828         277      21105
1        2018-01-01  제주시  50110670  ...         20828         277      21105
2        2018-01-01  제주시  50110670  ...         20828         277      21105
3        2018-01-01  제주시  50110670  ...         20828         277      21105
4        2018-01-01  제주시  50110670  ...         20828         277      21105
...             ...  ...       ...  ...           ...         ...        ...
2208909         NaN  NaN  50110330  ...          1722          27       1749
2208910         NaN  NaN  50110320  ...          1623         255       1878
2208911         NaN  NaN  50110330  ...          1719          27       1746
2208912         NaN  NaN  50110320  ...          1626         251       1877
2208913         NaN  NaN  50110330  ...          1722          29       1751

[2208914 rows x 15 columns]

In [ ]:
final[final['emd_nm_y']=='삼도1동']

          base_date city    emd_cd  ... resid_reg_pop foreign_pop  total_pop
24140    2018-01-01  제주시  50110550  ...         14405         141      14546
24141    2018-01-01  제주시  50110550  ...         14405         141      14546
24142    2018-01-01  제주시  50110550  ...         14405         141      14546
24143    2018-01-01  제주시  50110550  ...         14405         141      14546
24144    2018-01-01  제주시  50110550  ...         14405         141      14546
...             ...  ...       ...  ...           ...         ...        ...
2190601  2021-06-30  제주시  50110550  ...         13513         138      13651
2190602  2021-06-30  제주시  50110550  ...         13513         138      13651
2190603  2021-06-30  제주시  50110550  ...         13513         138      13651
2190604  2021-06-30  제주시  50110550  ...         13513         138      13651
2190605  2021-06-30  제주시  50110550  ...         13513         138      13651

[38080 rows x 15 columns]

In [ ]:
final['emd_nm'] = np.where(pd.isna(final['emd_nm_x']) == False, final['emd_nm_x'], final['emd_nm_y'])
final

          base_date city    emd_cd  ... foreign_pop total_pop  emd_nm
0        2018-01-01  제주시  50110670  ...         277     21105     외도동
1        2018-01-01  제주시  50110670  ...         277     21105     외도동
2        2018-01-01  제주시  50110670  ...         277     21105     외도동
3        2018-01-01  제주시  50110670  ...         277     21105     외도동
4        2018-01-01  제주시  50110670  ...         277     21105     외도동
...             ...  ...       ...  ...         ...       ...     ...
2208909         NaN  NaN  50110330  ...          27      1749     우도면
2208910         NaN  NaN  50110320  ...         255      1878     추자면
2208911         NaN  NaN  50110330  ...          27      1746     우도면
2208912         NaN  NaN  50110320  ...         251      1877     추자면
2208913         NaN  NaN  50110330  ...          29      1751     우도면

[2208914 rows x 16 columns]

In [ ]:
final = final.drop(['emd_nm_x','emd_nm_y'], axis=1)
final

          base_date city    emd_cd  ... foreign_pop  total_pop  emd_nm
0        2018-01-01  제주시  50110670  ...         277      21105     외도동
1        2018-01-01  제주시  50110670  ...         277      21105     외도동
2        2018-01-01  제주시  50110670  ...         277      21105     외도동
3        2018-01-01  제주시  50110670  ...         277      21105     외도동
4        2018-01-01  제주시  50110670  ...         277      21105     외도동
...             ...  ...       ...  ...         ...        ...     ...
2208909         NaN  NaN  50110330  ...          27       1749     우도면
2208910         NaN  NaN  50110320  ...         255       1878     추자면
2208911         NaN  NaN  50110330  ...          27       1746     우도면
2208912         NaN  NaN  50110320  ...         251       1877     추자면
2208913         NaN  NaN  50110330  ...          29       1751     우도면

[2208914 rows x 14 columns]

In [ ]:
final['emd_nm'].unique()

array(['외도동', '아라동', '노형동', '도두동', '오라동', '삼양동', '이도이동', '일도이동', '건입동',
       '화북동', '봉개동', '삼도일동', '이도일동', '용담이동', '연동', '이호동', '애월읍', '동홍동',
       '대정읍', '영천동', '서홍동', '효돈동', '중문동', '대륜동', '남원읍', '대천동', '안덕면',
       '천지동', '예래동', '표선면', '성산읍', '정방동', '송산동', '중앙동', '삼도이동', '일도일동',
       '용담일동', '조천읍', '구좌읍', '한경면', '한림읍', '추자면', '우도면'], dtype=object)

### 2) final + market

In [ ]:
market.columns

Index(['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'use_cnt', 'use_amt'],
      dtype='object')

In [ ]:
market.columns = ['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'm_use_cnt', 'm_use_amt']

In [ ]:
final2 = pd.merge(final, market, left_on=['base_date', 'city', 'emd_cd'], right_on=['base_date', 'city', 'emd_cd'], how='outer')
final2

          base_date city    emd_cd  ... mct_cat_nm  m_use_cnt   m_use_amt
0        2018-01-01  제주시  50110670  ...    마트/슈퍼마켓     1979.0  63631587.0
1        2018-01-01  제주시  50110670  ...    마트/슈퍼마켓     1979.0  63631587.0
2        2018-01-01  제주시  50110670  ...    마트/슈퍼마켓     1979.0  63631587.0
3        2018-01-01  제주시  50110670  ...    마트/슈퍼마켓     1979.0  63631587.0
4        2018-01-01  제주시  50110670  ...    마트/슈퍼마켓     1979.0  63631587.0
...             ...  ...       ...  ...        ...        ...         ...
2214207  2020-05-09  제주시  50110320  ...    마트/슈퍼마켓       36.0    410844.0
2214208  2020-09-20  제주시  50110320  ...    마트/슈퍼마켓       56.0    871919.0
2214209  2020-05-29  제주시  50110320  ...    마트/슈퍼마켓       46.0    955315.0
2214210  2021-04-21  제주시  50110320  ...    마트/슈퍼마켓       20.0    483577.0
2214211  2020-06-25  제주시  50110310  ...    마트/슈퍼마켓      230.0   9375693.0

[2214212 rows x 19 columns]

In [ ]:
final2['emd_nm'] = np.where(pd.isna(final2['emd_nm_x']) == False, final2['emd_nm_x'], final2['emd_nm_y'])
final2

          base_date city    emd_cd  ... m_use_cnt   m_use_amt  emd_nm
0        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
1        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
2        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
3        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
4        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
...             ...  ...       ...  ...       ...         ...     ...
2214207  2020-05-09  제주시  50110320  ...      36.0    410844.0     추자면
2214208  2020-09-20  제주시  50110320  ...      56.0    871919.0     추자면
2214209  2020-05-29  제주시  50110320  ...      46.0    955315.0     추자면
2214210  2021-04-21  제주시  50110320  ...      20.0    483577.0     추자면
2214211  2020-06-25  제주시  50110310  ...     230.0   9375693.0     한경면

[2214212 rows x 20 columns]

In [ ]:
final2 = final2.drop(['emd_nm_x','emd_nm_y','mct_cat_cd','mct_cat_nm'], axis=1)
final2

          base_date city    emd_cd  ... m_use_cnt   m_use_amt  emd_nm
0        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
1        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
2        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
3        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
4        2018-01-01  제주시  50110670  ...    1979.0  63631587.0     외도동
...             ...  ...       ...  ...       ...         ...     ...
2214207  2020-05-09  제주시  50110320  ...      36.0    410844.0     추자면
2214208  2020-09-20  제주시  50110320  ...      56.0    871919.0     추자면
2214209  2020-05-29  제주시  50110320  ...      46.0    955315.0     추자면
2214210  2021-04-21  제주시  50110320  ...      20.0    483577.0     추자면
2214211  2020-06-25  제주시  50110310  ...     230.0   9375693.0     한경면

[2214212 rows x 16 columns]

### 3) final2 + korean

In [ ]:
korean.columns

Index(['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'use_cnt', 'use_amt'],
      dtype='object')

In [ ]:
korean.columns = ['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'k_use_cnt', 'k_use_amt']

In [ ]:
final3 = pd.merge(final2, korean, left_on=['base_date', 'city', 'emd_cd'], right_on=['base_date', 'city', 'emd_cd'], how='outer')

In [ ]:
final3['emd_nm'] = np.where(pd.isna(final3['emd_nm_x']) == False, final3['emd_nm_x'], final3['emd_nm_y'])

In [ ]:
final3 = final3.drop(['emd_nm_x','emd_nm_y','mct_cat_cd','mct_cat_nm'], axis=1)
final3

          base_date city    emd_cd  ... k_use_cnt   k_use_amt  emd_nm
0        2018-01-01  제주시  50110670  ...    1124.0  39138494.0     외도동
1        2018-01-01  제주시  50110670  ...    1124.0  39138494.0     외도동
2        2018-01-01  제주시  50110670  ...    1124.0  39138494.0     외도동
3        2018-01-01  제주시  50110670  ...    1124.0  39138494.0     외도동
4        2018-01-01  제주시  50110670  ...    1124.0  39138494.0     외도동
...             ...  ...       ...  ...       ...         ...     ...
2214213  2018-01-26  제주시  50110330  ...      20.0    576925.0     우도면
2214214  2018-01-10  제주시  50110330  ...      15.0    126678.0     우도면
2214215  2020-02-17  제주시  50110330  ...      10.0    289575.0     우도면
2214216  2018-09-11  제주시  50110320  ...      25.0    505730.0     추자면
2214217  2019-11-18  제주시  50110330  ...      20.0    861900.0     우도면

[2214218 rows x 18 columns]

### 4) final3 + rest2

In [ ]:
rest2.columns

Index(['base_date', 'emd_cd', 'use_cnt', 'use_amt'], dtype='object')

In [ ]:
rest2.columns = ['base_date', 'emd_cd', 'r_use_cnt', 'r_use_amt']

In [ ]:
final4 = pd.merge(final3, rest2, left_on=['base_date', 'emd_cd'], right_on=['base_date', 'emd_cd'], how='outer')

In [ ]:
final4

          base_date city    emd_cd  ... emd_nm  r_use_cnt   r_use_amt
0        2018-01-01  제주시  50110670  ...    외도동      821.0  19951442.0
1        2018-01-01  제주시  50110670  ...    외도동      821.0  19951442.0
2        2018-01-01  제주시  50110670  ...    외도동      821.0  19951442.0
3        2018-01-01  제주시  50110670  ...    외도동      821.0  19951442.0
4        2018-01-01  제주시  50110670  ...    외도동      821.0  19951442.0
...             ...  ...       ...  ...    ...        ...         ...
2214213  2018-01-26  제주시  50110330  ...    우도면       10.0     84698.0
2214214  2018-01-10  제주시  50110330  ...    우도면       15.0    231752.0
2214215  2020-02-17  제주시  50110330  ...    우도면       15.0    319275.0
2214216  2018-09-11  제주시  50110320  ...    추자면       10.0    326515.0
2214217  2019-11-18  제주시  50110330  ...    우도면       10.0    408642.0

[2214218 rows x 20 columns]

### 5) final4 + ect2

In [ ]:
ect2.columns

Index(['base_date', 'emd_cd', 'use_cnt', 'use_amt'], dtype='object')

In [ ]:
ect2.columns = ['base_date', 'emd_cd', 'e_use_cnt', 'e_use_amt']

In [ ]:
final5 = pd.merge(final4, ect2, left_on=['base_date', 'emd_cd'], right_on=['base_date', 'emd_cd'], how='outer')

In [ ]:
final5

          base_date city    emd_cd  ...   r_use_amt  e_use_cnt   e_use_amt
0        2018-01-01  제주시  50110670  ...  19951442.0      374.0  14219262.0
1        2018-01-01  제주시  50110670  ...  19951442.0      374.0  14219262.0
2        2018-01-01  제주시  50110670  ...  19951442.0      374.0  14219262.0
3        2018-01-01  제주시  50110670  ...  19951442.0      374.0  14219262.0
4        2018-01-01  제주시  50110670  ...  19951442.0      374.0  14219262.0
...             ...  ...       ...  ...         ...        ...         ...
2214213  2018-01-26  제주시  50110330  ...     84698.0       20.0    507203.0
2214214  2018-01-10  제주시  50110330  ...    231752.0        NaN         NaN
2214215  2020-02-17  제주시  50110330  ...    319275.0        NaN         NaN
2214216  2018-09-11  제주시  50110320  ...    326515.0       15.0    467923.0
2214217  2019-11-18  제주시  50110330  ...    408642.0       15.0    482613.0

[2214218 rows x 22 columns]

### 6) final5 + deli

In [ ]:
deli.columns

Index(['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'use_cnt', 'use_amt'],
      dtype='object')

In [ ]:
deli.columns = ['base_date', 'city', 'emd_cd', 'emd_nm', 'mct_cat_cd', 'mct_cat_nm',
       'd_use_cnt', 'd_use_amt']

In [ ]:
final6 = pd.merge(final5, deli, left_on=['base_date', 'city', 'emd_cd'], right_on=['base_date', 'city', 'emd_cd'], how='outer')

In [ ]:
final6['emd_nm'] = np.where(pd.isna(final6['emd_nm_x']) == False, final6['emd_nm_x'], final6['emd_nm_y'])

In [ ]:
final6 = final6.drop(['emd_nm_x','emd_nm_y','mct_cat_cd','mct_cat_nm'], axis=1)
final6

          base_date city    emd_cd  ... d_use_cnt  d_use_amt  emd_nm
0        2018-01-01  제주시  50110670  ...      15.0   359412.0     외도동
1        2018-01-01  제주시  50110670  ...      15.0   359412.0     외도동
2        2018-01-01  제주시  50110670  ...      15.0   359412.0     외도동
3        2018-01-01  제주시  50110670  ...      15.0   359412.0     외도동
4        2018-01-01  제주시  50110670  ...      15.0   359412.0     외도동
...             ...  ...       ...  ...       ...        ...     ...
2214213  2018-01-26  제주시  50110330  ...      10.0   186580.0     우도면
2214214  2018-01-10  제주시  50110330  ...       NaN        NaN     우도면
2214215  2020-02-17  제주시  50110330  ...       5.0    79200.0     우도면
2214216  2018-09-11  제주시  50110320  ...       5.0   150246.0     추자면
2214217  2019-11-18  제주시  50110330  ...       NaN        NaN     우도면

[2214218 rows x 24 columns]

## correlation보기

In [ ]:
final6.columns

Index(['base_date', 'city', 'emd_cd', 'em_area_cd', 'em_cnt', 'em_g',
       'pay_amt', 'year_date', 'month_date', 'day_date', 'resid_reg_pop',
       'foreign_pop', 'total_pop', 'm_use_cnt', 'm_use_amt', 'k_use_cnt',
       'k_use_amt', 'r_use_cnt', 'r_use_amt', 'e_use_cnt', 'e_use_amt',
       'd_use_cnt', 'd_use_amt', 'emd_nm'],
      dtype='object')

In [ ]:
df = final6[['emd_cd', 'emd_nm', 'em_area_cd', 'em_cnt', 'em_g',
       'pay_amt', 'year_date', 'month_date', 'resid_reg_pop',
       'foreign_pop', 'm_use_cnt', 'm_use_amt', 'k_use_cnt',
       'k_use_amt', 'r_use_cnt', 'r_use_amt', 'e_use_cnt', 'e_use_amt',
       'd_use_cnt', 'd_use_amt']]
df

           emd_cd emd_nm em_area_cd  ...   e_use_amt  d_use_cnt  d_use_amt
0        50110670    외도동     W6X062  ...  14219262.0       15.0   359412.0
1        50110670    외도동     W6XA87  ...  14219262.0       15.0   359412.0
2        50110670    외도동     W6XA86  ...  14219262.0       15.0   359412.0
3        50110670    외도동     W6XA85  ...  14219262.0       15.0   359412.0
4        50110670    외도동     W6XA84  ...  14219262.0       15.0   359412.0
...           ...    ...        ...  ...         ...        ...        ...
2214213  50110330    우도면        NaN  ...    507203.0       10.0   186580.0
2214214  50110330    우도면        NaN  ...         NaN        NaN        NaN
2214215  50110330    우도면        NaN  ...         NaN        5.0    79200.0
2214216  50110320    추자면        NaN  ...    467923.0        5.0   150246.0
2214217  50110330    우도면        NaN  ...    482613.0        NaN        NaN

[2214218 rows x 20 columns]

In [ ]:
df.corr()

                 emd_cd    em_cnt      em_g  ...  e_use_amt  d_use_cnt  d_use_amt
emd_cd         1.000000 -0.045069  0.082849  ...  -0.400932  -0.279867  -0.264292
em_cnt        -0.045069  1.000000  0.862458  ...   0.144562   0.130563   0.119106
em_g           0.082849  0.862458  1.000000  ...   0.063297   0.059752   0.052795
pay_amt        0.055234  0.552108  0.686450  ...   0.039920   0.037529   0.033147
year_date     -0.009102 -0.078490 -0.082024  ...   0.087146   0.413488   0.407138
month_date     0.003579  0.041843  0.009464  ...   0.029740  -0.010073  -0.014046
resid_reg_pop -0.409662  0.166320  0.077438  ...   0.815481   0.616818   0.580415
foreign_pop   -0.080379  0.004304 -0.007222  ...   0.430489   0.371996   0.351157
m_use_cnt     -0.388780  0.224878  0.129228  ...   0.759796   0.621681   0.584964
m_use_amt     -0.309623  0.207450  0.125694  ...   0.745605   0.608043   0.572058
k_use_cnt     -0.454386  0.200474  0.101039  ...   0.798283   0.623615   0.583082
k_use_amt     -0.439566  0.199513  0.104779  ...   0.778910   0.589293   0.549118
r_use_cnt     -0.416314  0.203644  0.109058  ...   0.794191   0.591433   0.554201
r_use_amt     -0.404425  0.192900  0.104255  ...   0.769565   0.560661   0.524753
e_use_cnt     -0.453304  0.158393  0.064341  ...   0.901480   0.671463   0.635164
e_use_amt     -0.400932  0.144562  0.063297  ...   1.000000   0.587266   0.557150
d_use_cnt     -0.279867  0.130563  0.059752  ...   0.587266   1.000000   0.956933
d_use_amt     -0.264292  0.119106  0.052795  ...   0.557150   0.956933   1.000000

[18 rows x 18 columns]